### ISSUE TITLE
Just a note - Great asset

### ISSUE THREAD

**Issue by MostHated** [LeviMooreDev/Project-Planner#1]
Hey there,
    I had been using this since the day you released it and find it extremely useful, so I am sorry to see that you are finished with it, but can definitely understand and appreciate why. Even more so, I definitely appreciate you making the source available to the community when you were done with it instead of just keeping it up on the store and selling it with no plans on ever updating or supporting it, as far too many people seem to do. At least this way, community members can still get access and offer assistance with it when they can instead of it just being stuck and broken in future version of the editor.

A big thanks for that, and I wish you luck on your future endeavors. :+1: 
-MH

**Comment by LeviMooreDev** [comment]
Glad to hear that you have enjoyed Project Planner, and thanks for the support on the Asset Store. I have a lot of respect for the community, so this is the least I can do. Again thanks and all the best to you.

**Comment by MostHated** [comment]
I created a fork of the project and did some refactoring to be able to be installed via UPM https://github.com/instance-id/Project-Planner, I made sure to add notes in the package.json:

```json
"//": [
	  "Original by: LeviMooreDev : https://github.com/LeviMooreDev",
	  "Forked From: https://github.com/LeviMooreDev/Project-Planner"
]
```

**Comment by LeviMooreDev** [comment]
Great. Feel free to ask if you have questions about the code and I will try to help.
